// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, from ReScript");

function sum(x, y) {
  return x + y | 0;
}

console.log(2);

exports.sum = sum;
/*  Not a pure module */
