// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function sum(x, y) {
  return x + y | 0;
}

function conditionals(x) {
  var message = x === 0 ? "Nay" : (
      x === 1 ? "Yay" : "Yay... Nay..?"
    );
  console.log(message);
  
}

exports.sum = sum;
exports.conditionals = conditionals;
/* No side effect */
